export const PROJECTS = [
  {
    type: "title",
    text: "2024",
  },
  {
    type: "project",
    project: "GPT Enhanced",
    elevatorPitch: "Adding Whisper to chat.openai.com",
    status: "In Development",
    techStack: "Vite/Ts/React",
    imageUrl: "/misc/gpt-enhanced.png",
    role: "Software & Graphics",
    openSourceLink: null,
    link: null,
  },
  {
    type: "project",
    project: "Gemini Coach",
    elevatorPitch: "AI HR Coach for Googlers",
    status: "In Development",
    techStack: "Angular/Go Fiber",
    imageUrl: "/web-apps/gemini-coach.jpg",
    role: "Software & Graphics",
    openSourceLink: null,
    link: "https://gemini-coach.vercel.app/",
  },
  {
    type: "project",
    project: "Up It Quest",
    elevatorPitch: "Open source Leetcode Coaching",
    status: "In Development",
    techStack: "Nextjs/Tailwind",
    imageUrl: "/web-apps/up-it-quest.png",
    role: "Software & Graphics",
    openSourceLink: null,
    link: "https://upit.quest/",
  },
  {
    type: "title",
    text: "2023",
  },
  {
    type: "project",
    project: "AIOR",
    elevatorPitch: "AI Orchestrated Researching",
    status: "In Development",
    techStack: "T3-Stack (Nextjs, Prisma, Tailwind, TRPC)",
    imageUrl: "/web-apps/aior.jpg",
    role: "Software & Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Weather AR",
    elevatorPitch: "Weather based Augmented Reality app to overlay rain clouds in 3D space.",
    status: "Abandoned",
    techStack: "Unity C#, Python, Computer Vision",
    imageUrl: "/misc/clouds.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Meta Glasses - GPT4 Vision",
    elevatorPitch: "Added a hacky GPT4 Vision implementation to the Meta Glasses to enable automatic food logging via voice commands.",
    status: "Completed (Unreleased)",
    techStack: "Bun, Typescript",
    imageUrl: "/misc/glasses-food-log.png",
    role: "Software & Graphics",
    link: "https://www.youtube.com/watch?v=PiEDrcLCmew",
  },
  {
    type: "project",
    project: "Ourland",
    elevatorPitch: "Digital Australian Indigenous Map",
    status: "Released (Alpha)",
    techStack: "Nextjs, Prisma, Tailwind",
    imageUrl: "/web-apps/ourland.png",
    role: "Software & Graphics",
    link: "https://ourland.au",
  },
  {
    type: "project",
    project: "WatchGPT",
    elevatorPitch: "ChatGPT integrated into an Apple Watch",
    status: "Completed (Unreleased)",
    techStack: "Swift",
    imageUrl: "/misc/chat-watch.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Econ",
    elevatorPitch: "Apple Watch app that imports bank data to track spending %",
    status: "Completed (Unreleased)",
    techStack: "Swift, Go Fiber",
    imageUrl: "/misc/econ.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Hanzi Quiz",
    elevatorPitch: "Apple Watch app to quiz you on Chinese characters",
    status: "Completed (Unreleased)",
    techStack: "Swift, Go Fiber",
    imageUrl: "/misc/hanzi-quiz.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Hanzi Get",
    elevatorPitch: "Web scrapper to get Chinese characters from a website",
    status: "Completed (Unreleased)",
    techStack: "Bun, Typescript",
    imageUrl: "/misc/hanzi-get.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Jyutping for Flutter",
    elevatorPitch: "Flutter package to convert Chinese characters to Jyutping",
    status: "Completed (Released)",
    techStack: "Dart",
    imageUrl: "/misc/jyutping-for-flutter.png",
    role: "Software",
    link: "https://pub.dev/packages/jyutping",
  },
  {
    type: "project",
    project: "Hanzi Quest",
    elevatorPitch: "Mobile game to learn Chinese characters",
    status: "Released (Alpha)",
    techStack: "Unity C#",
    imageUrl: "/games/hanzi-quest.png",
    role: "Software & Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Up It APS",
    elevatorPitch: "An AI powered interview trainer for the Australian Public Service",
    status: "Released (Alpha)",
    techStack: "Qwik, Go Fiber",
    imageUrl: "/web-apps/up-it.png",
    role: "Software & Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Crunchy Scraper",
    elevatorPitch: "A web scraper to generate an ordered list of the top rated anime on Crunchyroll",
    status: "Released",
    techStack: "Javascript",
    imageUrl: "/misc/crunchy-roll-scraper.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "indigilang",
    elevatorPitch: "Research project to preserve Australian Indigenous languages using AI",
    status: "In Development",
    techStack: "Nextjs, Prisma, Tailwind, TRPC",
    imageUrl: "/web-apps/indigilang.png",
    role: "Software & Graphics",
    link: "https://indigilang.com.au",
  },
  {
    type: "project",
    project: "langpal",
    elevatorPitch: "An app for learning character based languages (like Mandarin, Cantonese, Korean etc).",
    status: "Released (Alpha)",
    techStack: "Flutter",
    imageUrl: "/mobile-apps/langpal.png",
    role: "Software & Graphics",
    link: "https://www.withlangpal.com",
  },
  {
    type: "project",
    project: "Artvuu Group",
    elevatorPitch: "Portfolio website for Artvuu Group",
    status: "Released",
    techStack: "Nextjs, Tailwind",
    imageUrl: "/web-apps/artvuu-group.png",
    role: "Software, Graphics",
    link: "https://artvuu.group",
  },
  {
    type: "title",
    text: "2022",
  },
  {
    type: "project",
    project: "Gram4r",
    elevatorPitch: "AI powered French grammar corrector",
    status: "Abandoned",
    techStack: "Nextjs",
    imageUrl: "/web-apps/gram4r.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Kitsune",
    elevatorPitch: "Relaxed infinite runner",
    status: "Released (Alpha)",
    techStack: "Unity C#",
    imageUrl: "/games/kitsune.jpg",
    role: "Software & Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Word Bloqs",
    elevatorPitch: "3D Wordle clone",
    status: "Released (Alpha)",
    techStack: "Unity C#",
    imageUrl: "/games/word-bloqs.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Yvettes Prologue",
    elevatorPitch: "Mobile and Desktop GBA styled game mixed between Dark Souls and Shadow of the Colossus",
    status: "Released (Alpha)",
    techStack: "Unity C#",
    imageUrl: "/games/yvettes-prologue.jpg",
    role: "Software, Graphics & Music",
    link: null,
  },
  {
    type: "project",
    project: "Quackers Party",
    elevatorPitch: "Duck based voice controlled party game",
    status: "Purgatory",
    techStack: "Unity C#",
    imageUrl: "/games/quackers-party.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "dashfl0w",
    elevatorPitch: "NFT investment analysis & tracking app",
    status: "Abandoned (lol)",
    techStack: "Nextjs, Nestjs",
    imageUrl: "/web-apps/dashfl0w.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Youtube Rating API",
    elevatorPitch: "API to automatically update the likes and dislikes of a creators Youtube videos",
    status: "Abandoned",
    techStack: "Nestjs",
    imageUrl: "/misc/youtube-rating-api.png",
    role: "Software",
    link: null,
  },
  {
    type: "title",
    text: "2021",
  },
  {
    type: "project",
    project: "Dwitter",
    elevatorPitch: "Inside joke app to remove all parts of Twitter expect the only feature a mate uses",
    status: "Completed (Unreleased)",
    techStack: "Flutter",
    imageUrl: "/mobile-apps/dwitter.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "title",
    text: "2020",
  },
  {
    type: "project",
    project: "Metro It",
    elevatorPitch: "Super efficient public transport app",
    status: "Purgatory",
    techStack: "Flutter",
    imageUrl: "/mobile-apps/metro-it.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "sition",
    elevatorPitch: "An app to convert your Spotify playlists into Youtube playlists",
    status: "Released (OpenSource)",
    techStack: "Flutter",
    imageUrl: "/mobile-apps/sition.png",
    role: "Software & Graphics",
    link: "https://www.withlangpal.com",
  },
  {
    type: "title",
    text: "2019",
  },
  {
    type: "project",
    project: "Poly Mountain",
    elevatorPitch: "Hyper Casual 2D infinite runner",
    status: "Purgatory",
    techStack: "Unity C#",
    imageUrl: "/games/poly-mountain.jpg",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Maze Flow",
    elevatorPitch: "Maze based infinite runner",
    status: "Released (Alpha)",
    techStack: "Unity C#",
    imageUrl: "/games/maze-flow.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "title",
    text: "2018",
  },
  {
    type: "project",
    project: "Waywind",
    elevatorPitch: "Casual Fishing RPG",
    status: "Abandoned",
    techStack: "Unity C#",
    imageUrl: "/games/waywind.jpg",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "title",
    text: "2017",
  },
  {
    type: "project",
    project: "Artvuu",
    elevatorPitch: "Virtual reality based Indigenous art gallery",
    status: "Abandoned",
    techStack: "Unity C#",
    imageUrl: "/mobile-apps/artvuu.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Kytls Quest",
    elevatorPitch: "Wave based pixel art top down RPG",
    status: "Released (Alpha)",
    techStack: "Unity C#",
    imageUrl: "/games/kytls-quest.jpg",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "title",
    text: "2016...",
  },
  {
    type: "project",
    project: "Skyveil",
    elevatorPitch: "3D low poly jet racing game",
    status: "Abandoned",
    techStack: "Unity C#",
    imageUrl: "/games/skyveil.gif",
    role: "Software & Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Cowboy Tap Tap",
    elevatorPitch: "Guitar hero-like pixel art cowboy duels",
    status: "Released (Alpha)",
    techStack: "Unity C#",
    imageUrl: "/games/cowboytaptap.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Ashers Descent",
    elevatorPitch: "4-bit dungeon crawler",
    status: "Released (Alpha)",
    techStack: "Unity C#",
    imageUrl: "/games/ashers-descent.jpg",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Chicken Chickens",
    elevatorPitch: "Chicken based pixel art RPG",
    status: "Abandoned",
    techStack: "Unity C#",
    imageUrl: "/games/chicken-chickens.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Anti Gravity Cartwheel Box",
    elevatorPitch: "Box based infinite runner",
    status: "Released (Alpha)",
    techStack: "Unity C#",
    imageUrl: "/games/agcb.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Down Up Challenge",
    elevatorPitch: "Fitness app based on the viral Bring Sally Up challenge",
    status: "Released (Beta)",
    techStack: "Android, Java",
    imageUrl: "/mobile-apps/downup.png",
    role: "Software, Graphics",
    link: null,
  },
  {
    type: "title",
    text: "2013 & Before 💀💀",
  },
  {
    type: "project",
    project: "A Bouncers Calculator",
    elevatorPitch: "Utility app for bouncers to determine if a person is allowed to enter a venue",
    status: "Released",
    techStack: "Windows Phone",
    imageUrl: null,
    role: "Software, Graphics",
    link: null,
  },
];
