export const INTRODUCTION_TEXT = "Hey how's it going. My name's Devon and I've been a software developer for the Australian Government for over 5 years - focusing on web development & innovation!";

export const PLAYER_SCENE_CONFIG = {
  typingSpeech: 43,
  speechSpeed: 200,
  playerSpeed: 5,
  runningAnimationSpeed: 0.55,
};

export const PROJECTS = [
  {
    type: "title",
    text: "2024",
  },
  {
    type: "project",
    project: "ChatGPT Enhanced",
    elevatorPitch: "Adding Whisper to chat.openai.com",
    status: "Released",
    techStack: "Chromium Extension API/Vite/Ts/React",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/4a908d08-8d15-4edb-759b-605b56767d00/public",
    openSourceLink: "https://github.com/dcrebbin/chatgpt-enhanced-extension",
    link: "https://chromewebstore.google.com/detail/chatgpt-enhanced/bpfpceoliebopalajhhgdpkepnkadlod",
  },
  {
    type: "project",
    project: "Gemini Coach",
    elevatorPitch: "AI HR Coach for Googlers",
    techStack: "Angular/Go Fiber",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/630433fe-7762-45fe-7f06-3de778991d00/public",
    openSourceLink: "https://github.com/dcrebbin/gemini-coach",
    link: "https://gemini-coach.vercel.app/",
  },
  {
    type: "project",
    project: "Up It Quest",
    elevatorPitch: "Open source Leetcode Coaching",
    techStack: "Nextjs/Tailwind",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/26a7dc88-7990-4825-5f6e-f9c678426100/public",
    openSourceLink: "https://github.com/dcrebbin/ai-interview-trainer-frontend",
    link: "https://upit.quest/",
  },
  {
    type: "project",
    project: "AI Audiobooks",
    elevatorPitch: "Convert your favourite books or text into audiobooks with python",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/01069253-244e-4f75-146e-8fa718b6c600/public",
    techStack: "Python",
    link: null,
    openSourceLink: "https://github.com/dcrebbin/ai-audiobooks",
  },
  {
    type: "project",
    project: "Youtube Channel to GPT",
    elevatorPitch: "Convert a Youtube channel into custom GPT model",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/da621df4-d231-4ad1-2f53-4e9eaf81cd00/public",
    techStack: "Python",
    link: null,
    openSourceLink: "https://github.com/dcrebbin/youtube-channel-to-gpt",
  },
  {
    type: "title",
    text: "2023",
  },
  {
    type: "project",
    project: "AIOR",
    elevatorPitch: "AI Orchestrated Researching",
    status: "Unreleased",
    techStack: "T3-Stack (Nextjs, Prisma, Tailwind, TRPC)",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/ec07af87-b839-4b32-049b-68aaa9e37200/public",
    link: null,
    verticalAspectRatio: true,
  },
  {
    type: "project",
    project: "Weather AR",
    elevatorPitch: "Weather based Augmented Reality app to overlay rain clouds in 3D space.",
    status: "Abandoned",
    techStack: "Unity C#, Python, Computer Vision",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/1c8d6b6f-480a-4870-4200-140bfc9c2d00/public",
    link: null,
  },
  {
    type: "project",
    project: "Meta Glasses - GPT4 Vision (Food Log)",
    elevatorPitch: "A hacky meta glasses api to connect to GPT4 Vision to log food",
    techStack: "Bun, Typescript",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/97c55ce2-9589-4f24-142c-24505e344b00/public",
    openSourceLink: "https://github.com/dcrebbin/meta-vision-api",
    link: "https://www.youtube.com/watch?v=PiEDrcLCmew",
  },
  {
    type: "project",
    project: "Ourland",
    elevatorPitch: "Digital Australian Indigenous Map",
    techStack: "Nextjs, Prisma, Tailwind",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/6baa9088-ba28-4e31-168a-36868b9ff200/public",
    link: "https://land.org.au",
  },
  {
    type: "project",
    project: "WatchGPT",
    elevatorPitch: "ChatGPT integrated into an Apple Watch",
    status: "Unreleased",
    techStack: "Swift",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/07c64242-bf10-4bf7-bffd-8e6cab48b800/public",
    link: null,
    verticalAspectRatio: true,
  },
  {
    type: "project",
    project: "Econ",
    elevatorPitch: "Apple Watch app that imports bank data to track spending %",
    status: "Unreleased",
    techStack: "Swift, Go Fiber",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/986aaa7c-43e0-4532-a7be-9c0bb12fae00/public",
    link: null,
    verticalAspectRatio: true,
  },
  {
    type: "project",
    project: "Hanzi Quiz",
    elevatorPitch: "Apple Watch app to quiz you on Chinese characters",
    status: "Unreleased",
    techStack: "Swift, Go Fiber",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/dc1255c8-e479-4b62-9c96-1875eca04700/public",
    link: null,
    verticalAspectRatio: true,
  },
  {
    type: "project",
    project: "Hanzi Get",
    elevatorPitch: "Web scrapper to get Chinese characters from a website",
    status: "Unreleased",
    techStack: "Bun, Typescript",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/7f1f5870-b7ab-4c75-9c33-940ee7656700/public",
    link: null,
  },
  {
    type: "project",
    project: "Jyutping for Flutter",
    elevatorPitch: "Flutter package to convert Chinese characters to Jyutping",
    techStack: "Dart",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/948b3736-d6a7-49f1-a82a-02b52175b700/public",
    link: "https://pub.dev/packages/jyutping",
  },
  {
    type: "project",
    project: "Hanzi Quest",
    elevatorPitch: "Web & Mobile game to learn Chinese characters",
    status: "Released",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/eeb5e04e-2093-4ee0-2902-0d7c59390700/public",
    link: "https://withlangpal.itch.io/hanzi-quest",
  },
  {
    type: "project",
    project: "Up It APS",
    elevatorPitch: "An AI powered interview trainer for the Australian Public Service",
    techStack: "Qwik, Go Fiber",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/2453d95c-2ea4-4b46-7616-2df264202c00/public",
    openSourceLink: "https://github.com/dcrebbin/up-it-aps-frontend",
    link: null,
  },
  {
    type: "project",
    project: "Crunchy Scraper",
    elevatorPitch: "A web scraper to generate an ordered list of the top rated anime on Crunchyroll",
    status: "Unreleased",
    techStack: "Javascript",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/51597b0f-8932-476f-5371-d2370c4c5f00/public",
    link: null,
  },
  {
    type: "project",
    project: "indigilang",
    elevatorPitch: "Research project to preserve Australian Indigenous languages using AI",
    techStack: "Nextjs, Prisma, Tailwind, TRPC",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/5834ad0f-e9b8-44e8-21f4-98cf440ea600/public",
    link: "https://indigilang.com.au",
  },
  {
    type: "project",
    project: "langpal",
    elevatorPitch: "An app for learning character based languages (like Mandarin, Cantonese, Korean etc).",
    techStack: "Flutter",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/2cb435cb-fd40-4a1c-772c-d12301f93f00/public",
    link: "https://withlangpal.com",
  },
  {
    type: "project",
    project: "Artvuu Group",
    elevatorPitch: "Portfolio website for Artvuu Group",
    status: "Abandoned",
    techStack: "Nextjs, Tailwind",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/a0ccd3dd-3f55-420a-6b89-049477003500/public",
    link: null,
  },
  {
    type: "title",
    text: "2022",
  },
  {
    type: "project",
    project: "Gram4r",
    elevatorPitch: "AI powered French grammar corrector",
    status: "Unreleased",
    techStack: "Nextjs",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/729b8742-d0e3-45b3-aa47-8d8e95bafb00/public",
    link: null,
  },
  {
    type: "project",
    project: "Kitsune",
    elevatorPitch: "Relaxed infinite runner [prototype]",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/bc7a1b52-9bad-452c-b685-34852e393400/public",
    link: "https://play.google.com/store/apps/details?id=com.PrototypePurgatory.kitsun3",
  },
  {
    type: "project",
    project: "Word Bloqs",
    elevatorPitch: "3D Wordle clone [prototype]",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/8823e051-ac29-43e0-f776-d09669b01500/public",
    link: "https://play.google.com/store/apps/details?id=com.PrototypePurgatory",
  },
  {
    type: "project",
    project: "Yvettes Prologue",
    elevatorPitch: "Mobile and Desktop GBA styled game mixed between Dark Souls and Shadow of the Colossus",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/12db1478-8654-413e-56de-e12361bf7000/public",
    link: "https://play.google.com/store/apps/details?id=com.PrototypePurgatory.YvettesPrologue",
  },
  {
    type: "project",
    project: "Quackers Party",
    elevatorPitch: "Duck based voice controlled party game",
    status: "Unreleased",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/ca7bb649-b774-427e-9e8d-086b1f136e00/public",
    link: null,
  },
  {
    type: "project",
    project: "dashfl0w",
    elevatorPitch: "NFT (lol) investment analysis & tracking app",
    status: "Abandoned",
    techStack: "Nextjs, Nestjs",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/5f2ba22b-c072-4e69-7374-230d55570700/public",
    link: null,
  },
  {
    type: "project",
    project: "Youtube Rating API",
    elevatorPitch: "API to automatically update the likes and dislikes of a creators Youtube videos",
    status: "Unreleased",
    techStack: "Nestjs",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/8573eb73-c13f-4b87-9388-e8ebed370400/public",
    link: null,
  },
  {
    type: "title",
    text: "2021",
  },
  {
    type: "project",
    project: "Dwitter",
    elevatorPitch: "Inside joke app to remove all parts of Twitter expect the only feature a mate uses",
    status: "Unreleased",
    techStack: "Flutter",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/2d03088f-abf3-4a20-6018-3ab332345a00/public",
    link: null,
    verticalAspectRatio: true,
  },
  {
    type: "title",
    text: "2020",
  },
  {
    type: "project",
    project: "Metro It",
    elevatorPitch: "Super efficient public transport app",
    status: "Abandoned",
    techStack: "Flutter",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/2d03088f-abf3-4a20-6018-3ab332345a00/public",
    link: null,
  },
  {
    type: "project",
    project: "Spotify to Youtube Playlist Converter",
    elevatorPitch: "An app to convert your Spotify playlists into Youtube playlists",
    techStack: "Flutter",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/8f0c7b8f-bb20-4b9d-f66f-e69a7e9bfa00/public",
    link: "https://github.com/dcrebbin/spotify-to-youtube-music",
    verticalAspectRatio: true,
  },
  {
    type: "title",
    text: "2019",
  },
  {
    type: "project",
    project: "Poly Mountain",
    elevatorPitch: "Hyper Casual 2D infinite runner",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/1546b551-b050-4cec-ef72-2b2fb5d62a00/public",
    link: "https://play.google.com/store/apps/details?id=com.PrototypePurgatory.PolyMountain",
    verticalAspectRatio: true,
  },
  {
    type: "project",
    project: "Maze Flow",
    elevatorPitch: "Maze based infinite runner",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/5352ed4a-cb6b-4f03-54e6-6faa0e2bf700/public",
    link: "https://play.google.com/store/apps/details?id=com.PrototypePurgatory.MazeFlow",
  },
  {
    type: "title",
    text: "2018",
  },
  {
    type: "project",
    project: "Waywind",
    elevatorPitch: "Casual Fishing RPG",
    status: "Abandoned",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/bab885a9-71ed-48ee-96c0-28350b60bd00/public",
    link: null,
  },
  {
    type: "title",
    text: "2017",
  },
  {
    type: "project",
    project: "Artvuu",
    elevatorPitch: "Virtual reality based Indigenous art gallery",
    status: "Abandoned",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/2296dcab-6ec7-4c03-43a9-28e959584900/public",
    link: null,
  },
  {
    type: "project",
    project: "Kytls Quest",
    elevatorPitch: "Wave based pixel art top down RPG",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/23486864-dfc6-4f96-cb82-962677dc8f00/public",
    link: "https://play.google.com/store/apps/details?id=com.PrototypePurgatory.KytlsQuest",
  },
  {
    type: "title",
    text: "2016...",
  },
  {
    type: "project",
    project: "Skyveil",
    elevatorPitch: "3D low poly jet racing game",
    status: "Abandoned",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/89481a12-a7f6-4463-3e80-f1045a1c0400/public",
    link: null,
  },
  {
    type: "project",
    project: "Cowboy Tap Tap",
    elevatorPitch: "Guitar hero-like pixel art cowboy duels",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/a8689f81-27b1-4511-e065-7dfb0b9e8c00/public",
    link: "https://play.google.com/store/apps/details?id=com.PrototypePurgatory.CowboyTapTap",
  },
  {
    type: "project",
    project: "Ashers Descent",
    elevatorPitch: "4-bit dungeon crawler",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/b8142255-6a3d-42d6-834f-d745aeaa0100/public",
    link: "https://play.google.com/store/apps/details?id=com.PrototypePurgatory.AshersDescent",
  },
  {
    type: "project",
    project: "Chicken Chickens",
    elevatorPitch: "Chicken based pixel art RPG",
    status: "Abandoned",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/2a80be59-9054-4fe0-270c-2c924d24a600/public",
    link: null,
  },
  {
    type: "project",
    project: "Anti Gravity Cartwheel Box",
    elevatorPitch: "Box based infinite runner",
    techStack: "Unity C#",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/4b428bbe-a2a4-45a3-1db5-6b3e6fbdf000/public",
    link: "https://play.google.com/store/apps/details?id=com.PrototypePurgatory.AGCB",
  },
  {
    type: "project",
    project: "Down Up Challenge",
    elevatorPitch: "Fitness app based on the viral Bring Sally Up challenge",
    techStack: "Android, Java",
    imageUrl: "https://imagedelivery.net/B-bofTeW0pZtEXxGfni94g/4821960e-f472-476b-c725-809fe9b22600/public",
    link: "https://play.google.com/store/apps/details?id=com.downupchallenge.downup",
    verticalAspectRatio: true,
  },
  {
    type: "title",
    text: "2013 & Before 💀💀",
  },
  {
    type: "project",
    project: "A Bouncers Calculator",
    elevatorPitch: "Utility app for bouncers to determine if a person is allowed to enter a venue",
    status: "Closed",
    techStack: "Windows Phone",
    imageUrl: null,
    link: null,
  },
];
