export const PROJECTS = [
  {
    type: "title",
    text: "2023",
  },
  {
    type: "project",
    project: "AIOR",
    elevatorPitch: "AI Orchestrated Researching",
    status: "In Development",
    techStack: "T3-Stack (Nextjs, Prisma, Tailwind, TRPC)",
    imageUrl: "/web-apps/aior.jpg",
    role: "Software & Graphics",
    link: null,
  },
  {
    type: "project",
    project: "Weather AR",
    elevatorPitch: "Weather based Augmented Reality app to overlay rain clouds in 3D space.",
    status: "Abandoned",
    techStack: "Unity C#, Python, Computer Vision",
    imageUrl: "/misc/clouds.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Meta Glasses - GPT4 Vision",
    elevatorPitch: "Added a hacky GPT4 Vision implementation to the Meta Glasses to enable automatic food logging via voice commands.",
    status: "Completed (Unreleased)",
    techStack: "Bun, Typescript",
    imageUrl: "/misc/glasses-food-log.png",
    role: "Software & Graphics",
    link: "https://www.youtube.com/watch?v=PiEDrcLCmew",
  },
  {
    type: "project",
    project: "Ourland",
    elevatorPitch: "Digital Australian Indigenous Map",
    status: "Released (Alpha)",
    techStack: "Nextjs, Prisma, Tailwind",
    imageUrl: "/web-apps/ourland.png",
    role: "Software & Graphics",
    link: "https://ourland.au",
  },
  {
    type: "project",
    project: "WatchGPT",
    elevatorPitch: "ChatGPT integrated into an Apple Watch",
    status: "Completed (Unreleased)",
    techStack: "Swift",
    imageUrl: "/misc/chat-watch.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Econ",
    elevatorPitch: "Apple Watch app that imports bank data to track spending %",
    status: "Completed (Unreleased)",
    techStack: "Swift, Go Fiber",
    imageUrl: "/misc/econ.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Hanzi Quiz",
    elevatorPitch: "Apple Watch app to quiz you on Chinese characters",
    status: "Completed (Unreleased)",
    techStack: "Swift, Go Fiber",
    imageUrl: "/misc/hanzi-quiz.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Hanzi Get",
    elevatorPitch: "Web scrapper to get Chinese characters from a website",
    status: "Completed (Unreleased)",
    techStack: "Bun, Typescript",
    imageUrl: "/misc/hanzi-get.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Jyutping for Flutter",
    elevatorPitch: "Flutter package to convert Chinese characters to Jyutping",
    status: "Completed (Released)",
    techStack: "Dart",
    imageUrl: "/misc/jyutping-for-flutter.png",
    role: "Software",
    link: null,
  },
  {
    type: "project",
    project: "Hanzi Quest",
    elevatorPitch: "Mobile game to learn Chinese characters",
    status: "Released (Alpha)",
    techStack: "Unity C#",
    imageUrl: "/games/hanzi-quest.png",
    role: "Software & Graphics",
    link: null,
  },
];
